<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/12/12
 * Time: 下午7:52
 */
namespace Admin\Controller;
use Think\Controller;
class AboutController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;  //分配栏目

    }

    /**
     * 关于我们
     */
    public function about(){
        $this->menu = ACTION_NAME;//分配小栏目

        $about = D('About');
        $action=I('get.action');

        if($action == 'save'){
            try{
                $about->saveInfo('1',$_POST['about']);
                $this->success('保存成功',U('about'));

            }catch ( Exception $e){
                //$page->back('保存信息失败,联系管理员');
                $this->error($e->getMessage());
            }
            exit;
        }else{
            $info = $about->getInfo('1','content');
            $this->assign('info', $info);
        }

        $this->display();

    }

    /**
     * 人才招聘
     */
    public function talented(){
        $this->menu = ACTION_NAME;//分配小栏目
        $about = D('About');
        $action=I('get.action');

        if($action == 'save'){
            try{
                $about->saveInfo('2',$_POST['talented']);
                $this->success('保存成功',U('talented'));


            }catch ( Exception $e){
                //$page->back('保存信息失败,联系管理员');
                $this->error($e->getMessage());
            }
            exit;
        }else{
            $info = $about->getInfo('2','content');
            $this->assign('info', $info);
        }

        $this->display();

    }

    /**
     * 用户协议
     */
    public function agreenment(){
        $this->menu = ACTION_NAME;//分配小栏目

        $about = D('About');
        $action=I('get.action');

        if($action == 'save'){
            try{
                $about->saveInfo('3',$_POST['agreement']);
                $this->success('保存成功',U('agreement'));


            }catch ( Exception $e){
                $this->error('保存信息失败,联系管理员');
                //$page->back($e->getMessage());
            }
            exit;
        }else{
            $info = $about->getInfo('3','content');
            $this->assign('info', $info);
        }

        $this->display();

    }
    /**
     * 版权声明
     */
    public function copyright(){
        $this->menu = ACTION_NAME;//分配小栏目

        $about = D('About');
        $action=I('get.action');

        if($action == 'save'){
            try{
                $about->saveInfo('4',$_POST['copyright']);
                $this->success('保存成功',U('copyright'));


            }catch ( Exception $e){
                //$page->back('保存信息失败,联系管理员');
                $this->error($e->getMessage());
            }
            exit;
        }else{
            $info = $about->getInfo('4','content');
            $this->assign('info', $info);
        }

        $this->display();

    }
    /**
     * 联系我们
     */
    public function contact(){
        $this->menu = ACTION_NAME;//分配小栏目

        $about = D('About');
        $action=I('get.action');

        if($action == 'save'){
            try{
                $about->saveInfo('5',$_POST['contact']);
                $this->success('保存成功',U('contact'));


            }catch ( Exception $e){
                $this->error('保存信息失败,联系管理员');
            }
            exit;
        }else{
            $info = $about->getInfo('5','content');
            $this->assign('info', $info);
        }

        $this->display();

    }
}