<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/12/12
 * Time: 下午8:38
 */

namespace Admin\Controller;
use Think\Controller;
class CityController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;  //分配栏目
    }

    /**
     * 城市管理
     */
    public function index(){
        $this->menu = ACTION_NAME;//分配小栏目

        $city = D('City');
        $action=I('get.action');
        if($action=='add'){

            $id = intval($_GET['id']);
            if($id){
                $dataInfo=$city->getInfo($id);
                $this->assign('dataInfo', $dataInfo);
            }

            $this->display('cityItemEdit');
            exit;

        }elseif($action=='save'){

            try{
                $city->saveInfo($_POST);
                $this->success('保存成功',U('index'));
            }catch (Exception $e){
                $this->error($e->getMessage());
            }
            exit;

        }elseif($action=='lock'){
            $ids = $_POST['ids'];
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择条目');
            }
            try{
                //锁定自己的条目
                $city->changeStatus($ids,1);
                $this->success('锁定成功',U('index'));

            }catch (Exception $e){
                $this->error($e->getMessage());
            }
            exit;

        }elseif($action=='unlock'){
            $ids = $_POST['ids'];
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择条目');
            }
            try{
                //解锁自己的条目
                $city->changeStatus($ids,0);
                $this->success('解锁成功',U('index'));
            }catch (Exception $e){
                $this->error($e->getMessage());
            }
            exit;

        }elseif($action=='delete'){
            $ids = $_POST['ids'];
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择删除条目');
            }
            try{
                //删除自己的条目
                $city->deleteInfo($ids);
                $this->success('删除成功',U('index'));
            }catch (Exception $e){
                $this->error($e->getMessage());
            }

            exit;

        }else{
            $where = '';
            $Page = new \Think\Page($city->getCount($where), 10);
            $Page->setConfig('header', '共%TOTAL_ROW%条');
            $Page->setConfig('first', '首页');
            $Page->setConfig('last', '共%TOTAL_PAGE%页');
            $Page->setConfig('prev', '上一页');
            $Page->setConfig('next', '下一页');
            $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
            $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

            $pageLimit = $Page->firstRow . ',' . $Page->listRows;
            $cityList = $city->getList($pageLimit,'*',$where,'pid asc ');
            $this->assign('dataList', $cityList);
            $this->assign('pagePanel', $Page->show());//分页条
        }
        $this->display();
    }
    /**
     * 加盟城市
     *
     */
    public function union(){

        $this->menu = ACTION_NAME;//分配小栏目

        $city = D('City');
        $action=I('get.action');
        $return_to = $_SERVER['HTTP_REFERER'];
        if($action=='delete'){
            $ids = $_POST['ids'];
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择删除条目');
            }
            try{
                $city->deleteUnion($ids);
                $this->success('删除加盟信息成功',$return_to);

            }catch (Exception $e){
                $this->error('删除失败，',$e->getMessage());
            }
            exit;

        }elseif($action=='dostatus'){
            $ids = $_POST['ids'];
            $status = intval($_GET['status']);
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择更改的信息');
            }

            try{
                $city->checkUnion($ids,$status);
                $this->success('状态修改成功',$return_to);

            }catch (Exception $e){
                $this->error($e->getMessage());
            }

            exit;

        }else{
            $check = intval($_GET['check']);
            $where = " and 1 = 1";
            $Page = new \Think\Page($city->getCountUnion($check,$where), 10);
            $Page->setConfig('header', '共%TOTAL_ROW%条');
            $Page->setConfig('first', '首页');
            $Page->setConfig('last', '共%TOTAL_PAGE%页');
            $Page->setConfig('prev', '上一页');
            $Page->setConfig('next', '下一页');
            $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
            $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

            $pageLimit = $Page->firstRow . ',' . $Page->listRows;
            $unionList = $city->getListUnion($pageLimit,'*',$check,$where,'time desc ');

            $this->assign('dataList', $unionList);
            $this->assign('pagePanel', $Page->show());//分页条
        }
        $this->display();

    }
}