<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/11/24
 * Time: 下午9:25
 */
namespace Admin\Controller;
use Think\Controller;
class CompanyManageController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;  //分配栏目
    }

    public function index(){
        $this->menu=ACTION_NAME;
        $company = D('Company');
        $type=I('get.type');
        $this->type=$type;
        $action=I('get.action');
        if($action=='edit'){

        }elseif($action=='add'){

            $this->action = I('get.action');

            $id = intval($_GET['id']);
            if($id){
                $dataInfo=$company->getInfo($id);
                $this->assign('dataInfo', $dataInfo);
            }
            //p($dataInfo);die;

        }elseif($action=='save'){
            $type = $_POST['company']['type'];
            if($_POST['id'] && empty($_POST['company']['passwd'])){
                unset($_POST['company']['passwd']);
            }else{
                $_POST['company']['passwd'] = md5($_POST['company']['passwd']);
            }
            if($company->saveCompany($_POST)){
                $this->success('保存成功',U('index').'/type/'.$type);
            }else{
                $this->error('保存失败');
            }

            exit;

        }elseif($action=="delete"){
            $back_url = $_SERVER['HTTP_REFERER'];
            $company_id = $_POST['ids'];
            if ($company_id) {
                try {
                    $company->deleteCompany($company_id);
                    $this->success('删除成功',$back_url);
                } catch (Exception $e) {
                    //echo $e->getMessage();
                    $this->error('删除失败',U('index').'/type/'.$type);
                }

            }
            exit;

        }elseif($action=='status'){
            $back_url = $_SERVER['HTTP_REFERER'];
            $ids = $_POST['ids'];
            $dostatus = intval($_GET['dostatus']);
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择需要操作的条目');
            }
            try{
                $company->changeStatus($ids,$dostatus);
                $this->success('操作成功',$back_url);
            }catch (Exception $e){
                $this->error($e->getMessage());
            }

            exit;

        }else {


            $Page = new \Think\Page($company->getCount(' and type=' . $type), 10);

            $Page->setConfig('header', '共%TOTAL_ROW%条');
            $Page->setConfig('first', '首页');
            $Page->setConfig('last', '共%TOTAL_PAGE%页');
            $Page->setConfig('prev', '上一页');
            $Page->setConfig('next', '下一页');
            $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
            $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

            $pageLimit = $Page->firstRow . ',' . $Page->listRows;


            $companyList = $company->getList($pageLimit, '*', ' and type=' . $type, '');
            $this->assign('companyList', $companyList);
            $this->assign('pagePanel', $Page->show());//分页条
        }

        $this->display();
    }

    public function add(){
        $this->display();
    }
}