<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/11/28
 * Time: 下午8:50
 */
namespace Admin\Controller;
use Think\Controller;
class MemberManageController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }

    /**
     * 经纪人列表
     */
    public function index(){
        $this->menu=ACTION_NAME;
        import('Class.Dd',APP_PATH);
        $member=D('Member');
        $where = '1=1 and user_type=1';
        if($_GET['status']){
            $where .= ' and status ='.intval($_GET['status']);
        }
        if($_GET['vip']){
            $where .= ' and vip ='.intval($_GET['vip']);
        }
        if($_GET['isindex']){
            $where .= ' and is_index ='.intval($_GET['isindex']);
        }
        if($_GET['is_open']){
            $where .= ' and is_open ='.intval($_GET['is_open']);
        }
        if($_GET['username']){
            $where .=" and username like '%".trim($_GET['username'])."%'";
        }

        if($_GET['realname']){
            $ids_realname = $member->searchMember('realname',trim($_GET['realname']));
        }
        if($_GET['tel']){
            $ids_tel = $member->searchMember('tel',trim($_GET['tel']));
        }
        if($_GET['email']){
            $where .=" and email like '%".trim($_GET['email'])."%'";
        }
        if($_GET['idcard']){
            $ids_idcard = $member->searchMember('idcard',trim($_GET['idcard']));
        }
        if($_GET['com']){
            $ids_com = $member->searchMember('com',trim($_GET['com']));
        }
        if($_GET['avatar']){
            $ids_avatar = $member->searchMember('avatar',$_GET['avatar']);
        }
        if($_GET['identity']){
            $ids_idcard = $member->searchMember('identity',$_GET['identity']);
        }
        if($_GET['realname'] || $_GET['tel'] || $_GET['email'] || $_GET['idcard'] || $_GET['com'] || $_GET['avatar'] || $_GET['identity'] ){
            $ids = array_merge((array)$ids_realname,(array)$ids_tel,(array)$ids_idcard,(array)$ids_com,(array)$ids_avatar,(array)$ids_idcard);
            $ids = array_unique($ids);
            if($ids){
                $where .=" and id in (".implode(',',$ids).")";
            }else{
                $where .=" and 0";
            }
        }
        $user_type = \Dd::getArray('user_type');

        $Page = new \Think\Page($member->getCount($where), 10);
        $Page->setConfig('header', '共%TOTAL_ROW%条');
        $Page->setConfig('first', '首页');
        $Page->setConfig('last', '共%TOTAL_PAGE%页');
        $Page->setConfig('prev', '上一页');
        $Page->setConfig('next', '下一页');
        $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
        $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

        $pageLimit = $Page->firstRow . ',' . $Page->listRows;
        $memberList = $member->getList($pageLimit,'*',$where,'add_time desc');
        foreach ($memberList as $key => $value){
            $memberList[$key]['member_info'] = $member->getMoreInfo($value['id'],1);
        }
        $this->assign('dataList', $memberList);
        $this->assign('pagePanel',$Page->show());//分页条
        $this->display();
    }

    public function changeName(){

        $this->title =  $this->title.' - 委托信息';

        $member = D('Member');
        $action=I('get.action');

        if($action == 'save'){
            //保存
            //p($_POST);die;
            $id = intval($_POST['id']);
            $_POST = charsetIconv($_POST);
            if($_POST['user_type'] == 1){
                $fieldData = array('realname'=>trim($_POST['realname']));
                $member->updateInfo($id,$fieldData,true,1);
            }else{
                $fieldData = array('first_name'=>trim($_POST['first_name']),'last_name'=>trim($_POST['last_name']));
                $member->updateInfo($id,$fieldData,true,2);
            }
            echo 1;
            exit;
        }else{

            if(!$_GET['id']){
                exit;
            }
            //编辑成交
            $id = intval($_GET['id']);
            $memberInfo = $member->getInfo($id,'*',true);

            $this->assign('dataInfo', $memberInfo);
        }

        $this->display();

    }
}