<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/11/27
 * Time: 下午8:32
 */
namespace Admin\Controller;
use Think\Controller;
class TrendManageController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;
    }

    /**
     * 总览图
     */
    public function index(){
        $this->menu=ACTION_NAME;
        $this->display();
    }

    /**
     * 二手房走势图
     */
    public function sell(){
        $this->menu=ACTION_NAME;
        $trend =D('HousesellTrend');
        $action=I('get.action');
        if($action=='edit'){


            if($_POST){
                if($_POST['id']){
                    //p($_POST);die;
                    //编辑
                    try {
                        $trend->saveTrend($_POST);
                    } catch (Exception $e) {
                        $this->error($e->getMessage(),U('sell').'/action/edit/id=' . $_GET['id']);
                    }
                }else{

                    $trendCount = $trend->getCount('time = "'.$_POST['timestr'].'"');
                    if($trendCount != 0){
                        $this->error('该月份已经存在');
                    }else{
                        try {
                            $trend->saveTrend($_POST);
                        } catch (Exception $e) {
                            $this->error($e->getMessage(),U('sell').'/action/edit/id=' . $_GET['id']);
                        }
                    }


                }

            }else{
                $id = $_GET['id'];
                $trendInfo = $trend->getInfo($id,'*');
                $this->assign('dataInfo', $trendInfo);
            }

        }elseif($action=='delete'){
            $back_to = $_SERVER['HTTP_REFERER'];
            $ids = $_POST['ids'];
            if(!is_array($ids) || empty($ids)){
                $this->error('没有选择删除条目');
            }
            try{
                $trend->deleteTrend($ids);
                $this->success('删除成功',U('sell'));
            }catch (Exception $e){
                $this->error($e->getMessage());
            }

            exit;

        }

            $Page = new \Think\Page($trend->getCount('1=1'), 10);
            $Page->setConfig('header', '共%TOTAL_ROW%条');
            $Page->setConfig('first', '首页');
            $Page->setConfig('last', '共%TOTAL_PAGE%页');
            $Page->setConfig('prev', '上一页');
            $Page->setConfig('next', '下一页');
            $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
            $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

            $pageLimit = $Page->firstRow . ',' . $Page->listRows;
            $list = $trend->getList($pageLimit,'*','1=1','time desc');
            $this->assign('list', $list);
            $this->assign('pagePanel', $Page->show());//分页条

        $this->display();
    }
}