<?php
/**
 * Created by PhpStorm.
 * User: david
 * Date: 16/11/27
 * Time: 下午9:42
 */
namespace Admin\Controller;
use Think\Controller;
class UserManageController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cate=CONTROLLER_NAME;

    }

    /**
     * 用户列表
     */
    public function index(){
        $this->menu=ACTION_NAME;

        $user = D('Users');
        $_GET['user_id'] = intval($_GET['user_id']);
        $action=I('get.action');

        //$user->allow('user');
        $Page = new \Think\Page($user->getCount(), 10);
        $Page->setConfig('header', '共%TOTAL_ROW%条');
        $Page->setConfig('first', '首页');
        $Page->setConfig('last', '共%TOTAL_PAGE%页');
        $Page->setConfig('prev', '上一页');
        $Page->setConfig('next', '下一页');
        $Page->setConfig('link', 'indexpagenumb');//pagenumb 会替换成页码
        $Page->setConfig('theme', '%HEADER% %FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END%');

        $pageLimit = $Page->firstRow . ',' . $Page->listRows;
        $userList = $user->getList($pageLimit);

        //分页类
        $this->assign('userList', $userList);
        $this->assign('pagePanel', $Page->show());//分页条

        $this->display();
    }

    /**
     * 添加用户
     */
    public function addUser(){
        $user = D('Users');

        if ($_GET['user_id']) {
            $userInfo = $user->getInfo($_GET['user_id']);
            $this->assign('userInfo', $userInfo);
            $this->assign('user_id', $_GET['user_id']);
        }
        $group = D('Group');
        $select = $group->getSelect($userInfo['group_id']);
        $this->assign('select', $select);
        $this->display();
    }

    /**
     * 保存用户
     */
    public function saveUser(){

        $user = D('Users');

        if( $_POST['user_id'] =="" && $user->getAllUsers('*',"username ='".$_POST['username']."'")){
            $this->error('用户已存在');
        }
        if($user->saveUsers($_POST)){
            $this->success('保存成功',U('index'));
        }else{
            $this->error('增加用户失败');
        }


    }

    /**
     * 删除用户
     */
    public function deleteUser(){
        $user = D('Users');

        $users = $_GET['user_id'] ? $_GET['user_id'] : $_POST['users'];
        if ($users) {
            try {
                $item = array('isdel' => 1);

                $flag = false;
                if (is_array($users)) {
                    if (in_array(1, $users)) {//1是admin的id
                        $flag = true;
                    }
                    $users = implode(',',$users);
                    $where = 'user_id in (' . $users . ')';
                } else {
                    if (1==$users) {
                        $flag = true;
                    }
                    $where = 'user_id=' . intval($users);
                }
                if ($flag) {
                    $this->error('系统管理员不能够被删除！');
                }
                $user->deleteUser($users);
            } catch (Exception $e) {
                echo $e->getMessage();

            }

        }
    }




}